[options]
addons_path = d:/A_Coding/Odoo_2026/odoo/addons,d:/A_Coding/Odoo_2026
admin_passwd = CyberKush_admin_security
db_host = localhost
db_port = 5432
db_user = odoo_user
db_password = CyberKush
db_name = assetflow_db
